#!/bin/bash

# downallapt

# EN: Download all .deb packages from an apt repository.
# ES: Descarga todos los ficheros de los repositorios.

# Author / Autor: Charlie Martínez <cmartinez@quirinux.org>
# GPLv2 License - https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

# -------------------------ENGLISH---------------------------------------

# How it works:

# Download all the files from the repositories
# that are enabled in /etc/apt/sources.list and /etc/apt/sources.list.d
# and save them in a new / packages folder

# Instructions:

# Comment those repositories in /etc/apt/sources.list and /etc/apt/sources.list.d that we do not want to download.

# Run as root:

# chmod 755 downallapt
# mv downallapt /usr/local/bin/downallapt
# downallapt

# -----------------------CASTELLANO-----------------------------

# Cómo funciona:

# que estén habilitados en /etc/apt/sources.list y /etc/apt/sources.list.d
# y los guarda en una nueva carpeta /packages

# Instrucciones:
 
# Comentar aquellos repositorios en /etc/apt/sources.list y /etc/apt/sources.list.d que no queremos descargar.

# Ejecutar como root:

# chmod 755 downallapt
# mv downallapt /usr/local/bin/downallapt
# downallapt


FILE="./packages"

if [ -e ${FILE} ]; then
rm -rf ./packages
fi

mkdir packages
cd packages
apt-cache  dumpavail |grep -oP "(?<=Package: ).*" >> packagelist
for package in `cat packagelist`
 do
    apt-get download $package 
 done

