#!/bin/bash

# -------------------------ENGLISH---------------------------------------

#downallapt

# Download all .deb packages from an apt repository

# Author: Charlie Martínez <cmartinez@quirinux.org>
# GPLv2 License - https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

# How it works:

# Download all the files from the repositories
# that are enabled in /etc/apt/sources.list and /etc/apt/sources.list.d
# and save them in a new / packages folder

# Instructions:
 
# Run as root.
# Comment those repositories in /etc/apt/sources.list and /etc/apt/sources.list.d that we do not want to download. 

# -----------------------CASTELLANO-----------------------------

# downallapt

# Descargar todos los paquetes .deb de un repositorio apt

# Author: Charlie Martínez <cmartinez@quirinux.org>
# Licencia GPLv2 - https://www.gnu.org/licenses/old-licenses/gpl-2.0.html

# Cómo trabaja:

# Descarga todos los ficheros de los repositorios
# que estén habilitados en /etc/apt/sources.list y /etc/apt/sources.list.d
# y los guarda en una nueva carpeta /packages

# Instrucciones:
 
# Ejecutar como root.
# Comentar aquellos repositorios en /etc/apt/sources.list y /etc/apt/sources.list.d que no queremos descargar.


FILE="./packages"

if [ -e ${FILE} ]; then
rm -rf ./packages
fi

mkdir packages
cd packages
apt-cache  dumpavail |grep -oP "(?<=Package: ).*" >> packagelist
for package in `cat packagelist`
 do
    apt-get download $package 
 done

